### ISSUE TITLE
Improve Text Rendering Under Non-Integer Scaling

### ISSUE THREAD

**Issue by LPGhatguy** [SecondHalfGames/yakui#1]
Text looks funny under 1.25x scaling.

![ApplicationFrameHost_e5smdAD4e8](https://user-images.githubusercontent.com/654598/179479418-3e9dd099-df78-4659-989a-5166d5dc0f44.png)

**Comment by sapir** [comment]
I think that what's happening is that fontdue is already rounding the glyph positions. e.g. The documentation for `GlyphPosition.x` says that it's always a whole number. Then when you scale it up, the rounding error is multiplied.

**Comment by LPGhatguy** [comment]
502b67f946764a555325f4d61361ba84578fb38d was a minor improvement here based on your comment on #36.

**Comment by LPGhatguy** [comment]
cosmic text fixed this fully!
